//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace com::ianlee::FezHat;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<FezHatSetRedLedStateResult^>^ FezHatServiceEventAdapter::SetRedLedStateAsync(_In_ AllJoynMessageInfo^ info, _In_ bool interfaceMemberOn)
{
    auto args = ref new FezHatSetRedLedStateCalledEventArgs(info, interfaceMemberOn);
    AllJoynHelpers::DispatchEvent([=]() {
        SetRedLedStateCalled(this, args);
    });
    return FezHatSetRedLedStateCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<FezHatGetRedLedStateResult^>^ FezHatServiceEventAdapter::GetRedLedStateAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new FezHatGetRedLedStateCalledEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetRedLedStateCalled(this, args);
    });
    return FezHatGetRedLedStateCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<FezHatSetRgbLedD2ColorResult^>^ FezHatServiceEventAdapter::SetRgbLedD2ColorAsync(_In_ AllJoynMessageInfo^ info, _In_ bool interfaceMemberOn, _In_ byte interfaceMemberRed, _In_ byte interfaceMemberGreen, _In_ byte interfaceMemberBlue)
{
    auto args = ref new FezHatSetRgbLedD2ColorCalledEventArgs(info, interfaceMemberOn, interfaceMemberRed, interfaceMemberGreen, interfaceMemberBlue);
    AllJoynHelpers::DispatchEvent([=]() {
        SetRgbLedD2ColorCalled(this, args);
    });
    return FezHatSetRgbLedD2ColorCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<FezHatSetRgbLedD3ColorResult^>^ FezHatServiceEventAdapter::SetRgbLedD3ColorAsync(_In_ AllJoynMessageInfo^ info, _In_ bool interfaceMemberOn, _In_ byte interfaceMemberRed, _In_ byte interfaceMemberGreen, _In_ byte interfaceMemberBlue)
{
    auto args = ref new FezHatSetRgbLedD3ColorCalledEventArgs(info, interfaceMemberOn, interfaceMemberRed, interfaceMemberGreen, interfaceMemberBlue);
    AllJoynHelpers::DispatchEvent([=]() {
        SetRgbLedD3ColorCalled(this, args);
    });
    return FezHatSetRgbLedD3ColorCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<FezHatGetLightSensorValueResult^>^ FezHatServiceEventAdapter::GetLightSensorValueAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new FezHatGetLightSensorValueCalledEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetLightSensorValueCalled(this, args);
    });
    return FezHatGetLightSensorValueCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<FezHatGetTemperatureSensorValueResult^>^ FezHatServiceEventAdapter::GetTemperatureSensorValueAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new FezHatGetTemperatureSensorValueCalledEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetTemperatureSensorValueCalled(this, args);
    });
    return FezHatGetTemperatureSensorValueCalledEventArgs::GetResultAsync(args);
}

// Property Reads
// Property Writes
