//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace ianlee { namespace FezHat {

ref class FezHatConsumer;

public ref class FezHatSetRedLedStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static FezHatSetRedLedStateResult^ CreateSuccessResult()
    {
        auto result = ref new FezHatSetRedLedStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static FezHatSetRedLedStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new FezHatSetRedLedStateResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class FezHatGetRedLedStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool State
    {
        bool get() { return m_interfaceMemberState; }
    internal:
        void set(_In_ bool value) { m_interfaceMemberState = value; }
    }
    
    static FezHatGetRedLedStateResult^ CreateSuccessResult(_In_ bool interfaceMemberState)
    {
        auto result = ref new FezHatGetRedLedStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->State = interfaceMemberState;
        return result;
    }
    
    static FezHatGetRedLedStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new FezHatGetRedLedStateResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    bool m_interfaceMemberState;
};

public ref class FezHatSetRgbLedD2ColorResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static FezHatSetRgbLedD2ColorResult^ CreateSuccessResult()
    {
        auto result = ref new FezHatSetRgbLedD2ColorResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static FezHatSetRgbLedD2ColorResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new FezHatSetRgbLedD2ColorResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class FezHatSetRgbLedD3ColorResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static FezHatSetRgbLedD3ColorResult^ CreateSuccessResult()
    {
        auto result = ref new FezHatSetRgbLedD3ColorResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static FezHatSetRgbLedD3ColorResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new FezHatSetRgbLedD3ColorResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class FezHatGetLightSensorValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double Value
    {
        double get() { return m_interfaceMemberValue; }
    internal:
        void set(_In_ double value) { m_interfaceMemberValue = value; }
    }
    
    static FezHatGetLightSensorValueResult^ CreateSuccessResult(_In_ double interfaceMemberValue)
    {
        auto result = ref new FezHatGetLightSensorValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Value = interfaceMemberValue;
        return result;
    }
    
    static FezHatGetLightSensorValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new FezHatGetLightSensorValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    double m_interfaceMemberValue;
};

public ref class FezHatGetTemperatureSensorValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double ValueC
    {
        double get() { return m_interfaceMemberValueC; }
    internal:
        void set(_In_ double value) { m_interfaceMemberValueC = value; }
    }
    property double ValueF
    {
        double get() { return m_interfaceMemberValueF; }
    internal:
        void set(_In_ double value) { m_interfaceMemberValueF = value; }
    }
    
    static FezHatGetTemperatureSensorValueResult^ CreateSuccessResult(_In_ double interfaceMemberValueC, _In_ double interfaceMemberValueF)
    {
        auto result = ref new FezHatGetTemperatureSensorValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->ValueC = interfaceMemberValueC;
        result->ValueF = interfaceMemberValueF;
        return result;
    }
    
    static FezHatGetTemperatureSensorValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new FezHatGetTemperatureSensorValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    double m_interfaceMemberValueC;
    double m_interfaceMemberValueF;
};

public ref class FezHatJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property FezHatConsumer^ Consumer
    {
        FezHatConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ FezHatConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    FezHatConsumer^ m_consumer;
};

} } } 
